; ; PlatformIO Projektkonfiguration für LILYGO T-Energy-S3
; ; ESP32-Sender/Empfänger mit ESP-NOW

; [env:lilygo_tenergy_s3]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino

; monitor_speed = 115200
; monitor_filters = esp32_exception_decoder

; ; Build-Optimierungen
; build_type = release
; board_build.flash_mode = qio
; board_build.f_cpu = 240000000L

; ; Compiler-Flags
; build_flags =
;   -DCORE_DEBUG_LEVEL=0
;   -DBOARD_HAS_PSRAM
;   -DLILYGO_TENERGY_S3
;   -Og
;   -ffunction-sections
;   -fdata-sections
;   -Wl,--gc-sections
;   -DARDUINO_USB_MODE=1
;   -DARDUINO_USB_CDC_ON_BOOT=1

; ; Libraries – KEINE externe ESP-NOW-Lib!
; lib_deps =

; ; Partition-Schema
; board_build.partitions = default_16MB.csv
; board_upload.flash_size = 16MB

; ; Upload-Einstellungen
; upload_protocol = esptool
; upload_speed = 921600


[env:lilygo_tenergy_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_type = debug
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=5

lib_deps =
